### ISSUE TITLE
potential problem of gcov-tool-many

### ISSUE THREAD

**Issue by weixlu** [yugr/maintainer-scripts#2]
Hi, thanks for your contributions of so many helpful scripts here. I have tried `gcov-tool-many` to merge multiple gcda files and found a potential problem.
It seems the merge here is barely a simpy iteration. For example, to merge `file1` `file2` and `file3`, the script will conduct
```
gcov-tool merge -o tmp1 file1 file2
gcov-tool merge -o  result tmp1 file3
```
However, I guess tmp1 should weigh more than file3, since tmp1 is a combination of file1 and file2. That is
```
gcov-tool merge -o tmp1 file1 file2
gcov-tool merge -o  result tmp1 file3 --weight 2:1
```
I'm not sure whether we should set a weight here, or just leave it by default. What do you think?

**Comment by yugr** [comment]
First of all, thank you for your interest in this repo.

> However, I guess tmp1 should weigh more than file3, since tmp1 is a combination of file1 and file2

Could you provide an example of an error?

I tried with a simple example like this one:
```
#include <stdio.h>
#include <string.h>

int main(int argc, char *argv[]) {
  if (strcmp(argv[1], "1") == 0) {
    printf("A\n");
  } else if (strcmp(argv[1], "2") == 0) {
    printf("B\n");
  } else {
    printf("C\n");
  }
  return 0;
}
```

I then run it three times
```
rm -rf a.out data tmp.gc* *.gcov

gcc --coverage tmp.c

mkdir -p data/1
./a.out 1
mv a-tmp.gcda data/1

mkdir -p data/2
./a.out 2
mv a-tmp.gcda data/2

mkdir -p data/3
./a.out 3
mv a-tmp.gcda data/3
```
and combine results via `gcov-tool`:
```
gcov-tool merge data/1 data/2 -o data/12
gcov-tool merge data/12 data/3 -o data/123
```

Then I generate coverage report
```
cp a-tmp.gcno data/123
gcov data/123/a-tmp.gcda
```
and get a reasonable output:
```
        -:    0:Source:tmp.c
        -:    0:Graph:data/123/a-tmp.gcno
        -:    0:Data:data/123/a-tmp.gcda
        -:    0:Runs:3
        -:    1:#include <stdio.h>
        -:    2:#include <string.h>
        -:    3:
        3:    4:int main(int argc, char *argv[]) {
        3:    5:  if (strcmp(argv[1], "1") == 0) {
        1:    6:    printf("A\n");
        2:    7:  } else if (strcmp(argv[1], "2") == 0) {
        1:    8:    printf("B\n");
        -:    9:  } else {
        1:   10:    printf("C\n");
        -:   11:  }
        3:   12:  return 0;
        -:   13:}
        -:   14:
```

As you can see all execution counts are reasonable e.g. line 5 is executed three times and each `printf` is executed just once.

**Comment by weixlu** [comment]
It seems I misunderstand how the merge procedure goes. I expected it to calculate a weighted average rather than a counter accumulation, which proves to be incorrect according to your example. Then the script `gcov-tool-many` works out fine. Thanks for your detailed explanations.
